export const CategoryConstants = {
    GET_ALL_CATEGORIES: "GET_ALL_CATEGORIES",
    GET_ALL_CATEGORIES_SUCCESS: "GET_ALL_CATEGORIES_SUCCESS",
    GET_ALL_CATEGORIES_FAILED: "GET_ALL_CATEGORIES_FAILED",
    PROGRAMMING:"PROGRAMMING",
    BUSINESS:"BUSINESS",
    MARKETING:"MARKETING",
    ENGINEERING:"ENGINEERING",
    CHANGE_CATEGORY_TO_DIPLAY:"CHANGE_CATEGORY_TO_DIPLAY",
    GET_CURRENT_CATEGORY_WITH_TOPICS:"GET_CURRENT_CATEGORY_WITH_TOPICS",
    GET_CURRENT_CATEGORY_WITH_TOPICS_SUCCESS:"GET_CURRENT_CATEGORY_WITH_TOPICS_SUCCESS",
    GET_CURRENT_CATEGORY_WITH_TOPICS_FAILED:"GET_CURRENT_CATEGORY_WITH_TOPICS_FAILED",
}