export const CourseConstant= {
    GET_BEST_SELLER_COURSE: "GET_BEST_SELLER_COURSE",
    GET_BEST_SELLER_COURSE_SUCCESS: "GET_BEST_SELLER_COURSE_SUCCESS",
    GET_BEST_SELLER_COURSE_FAILED: "GET_BEST_SELLER_COURSE_FAILED",
    
    GET_TOP_6_COURSES_BY_CATEGORY:"GET_TOP_6_COURSES_BY_CATEGORY",
    GET_TOP_6_COURSES_BY_CATEGORY_SUCCESS:"GET_TOP_6_COURSES_BY_CATEGORY_SUCCESS",
    GET_TOP_6_COURSES_BY_CATEGORY_FAILED:"GET_TOP_6_COURSES_BY_CATEGORY_FAILED",
    
    GET_TOP_RATING_COURSE:"GET_TOP_RATING_COURSE",
    GET_TOP_RATING_COURSE_SUCCESS:"GET_TOP_RATING_COURSE_SUCCESS",
    GET_TOP_RATING_COURSE_FAILED:"GET_TOP_RATING_COURSE_FAILED",

    GET_CURRENT_COURSES_BY_CATEGORY:"GET_CURRENT_COURSES_BY_CATEGORY",
    GET_CURRENT_COURSES_BY_CATEGORY_SUCCESS:"GET_CURRENT_COURSES_BY_CATEGORY_SUCCESS",
    GET_CURRENT_COURSES_BY_CATEGORY_FAILED:"GET_CURRENT_COURSES_BY_CATEGORY_FAILED",

    GET_COURSE_DETAIL:"GET_COURSE_DETAIL",
    GET_COURSE_DETAIL_SUCCESS:"GET_COURSE_DETAIL_SUCCESS",
    GET_COURSE_DETAIL_SUCCESS_FAIL:"GET_COURSE_DETAIL_SUCCESS_FAIL",

    GET_COURSES_BY_INSTRUCTOR:"GET_COURSES_BY_INSTRUCTOR",
    GET_COURSES_BY_INSTRUCTOR_SUCCESS:"GET_COURSES_BY_INSTRUCTOR_SUCCESS",
    GET_COURSES_BY_INSTRUCTOR_FAIL:"GET_COURSES_BY_INSTRUCTOR_FAIL",

    GET_COURSES_OF_STUDENT:"GET_COURSES_OF_STUDENT",
    GET_COURSES_OF_STUDENT_SUCCESS:"GET_COURSES_OF_STUDENT_SUCCESS",
    GET_COURSES_OF_STUDENT_FAIL:"GET_COURSES_OF_STUDENT_FAIL",

    GET_USER_COURSE_LESSONS:"GET_USER_COURSE_LESSONS",
    GET_USER_COURSE_LESSONS_SUCCESS:"GET_USER_COURSE_LESSONS_SUCCESS",
    GET_USER_COURSE_LESSONS_FAIL:"GET_USER_COURSE_LESSONS_FAIL",

    GET_STUDENT_COURSE_SECTION_LIST: "GET_STUDENT_COURSE_SECTION_LIST",
    GET_STUDENT_COURSE_SECTION_LIST_SUCCESS:"GET_STUDENT_COURSE_SECTION_LIST_SUCCESS",
    GET_STUDENT_COURSE_SECTION_LIST_FAIL:"GET_STUDENT_COURSE_SECTION_LIST_FAIL", 

    GET_SECTION_DETAIL:"GET_SECTION_DETAIL",
    GET_SECTION_DETAIL_SUCCESS:"GET_SECTION_DETAIL_SUCCESS",
    GET_SECTION_DETAIL_FAIL:"GET_SECTION_DETAIL_FAIL",

    CHANGE_CURRENT_SECTION:"CHANGE_CURRENT_SECTION",
    CHANGE_CURRENT_LESSON:"CHANGE_CURRENT_LESSON",

    GET_COURSE_LIST_MANAGEMENT:"GET_COURSE_LIST_MANAGEMENT",
    GET_COURSE_LIST_MANAGEMENT_SUCCESS:"GET_COURSE_LIST_MANAGEMENT_SUCCESS",
    GET_COURSE_LIST_MANAGEMENT_FAIL:"GET_COURSE_LIST_MANAGEMENT_FAIL",
    
    CREATE_NEW_COURSE:"CREATE_NEW_COURSE",
    CREATE_NEW_COURSE_SUCESS:"CREATE_NEW_COURSE_SUCESS",
    CREATE_NEW_COURSE_FAIL:"CREATE_NEW_COURSE_FAIL",

    GET_LESSON_LIST_MANAGEMENT:"GET_LESSON_LIST_MANAGEMENT",
    GET_LESSON_LIST_MANAGEMENT_SUCCESS:"GET_LESSON_LIST_MANAGEMENT_SUCCESS",
    GET_LESSON_LIST_MANAGEMENT_FAIL:"GET_LESSON_LIST_MANAGEMENT_FAIL",

    GET_LESSON_MANAGEMENT:"GET_LESSON_MANAGEMENT",
    GET_LESSON_MANAGEMENT_SUCCESS:"GET_LESSON_MANAGEMENT_SUCCESS",
    GET_LESSON_MANAGEMENT_FAIL:"GET_LESSON_MANAGEMENT_FAIL",

    GET_SECTION_LIST_MANAGEMENT:"GET_SECTION_LIST_MANAGEMENT",
    GET_SECTION_LIST_MANAGEMENT_SUCCESS:"GET_SECTION_LIST_MANAGEMENT_SUCCESS",
    GET_SECTION_LIST_MANAGEMENT_FAIL:"GET_SECTION_LIST_MANAGEMENT_FAIL",

    GET_SECTION_UPDATE:"GET_SECTION_UPDATE",
    GET_SECTION_UPDATE_SUCCESS:"GET_SECTION_UPDATE_SUCCESS",
    GET_SECTION_UPDATE_FAIL:"GET_SECTION_UPDATE_FAIL"

}