export const CourseConstant= {
    GET_BEST_SELLER_COURSE: "GET_BEST_SELLER_COURSE",
    GET_BEST_SELLER_COURSE_SUCCESS: "GET_BEST_SELLER_COURSE_SUCCESS",
    GET_BEST_SELLER_COURSE_FAILED: "GET_BEST_SELLER_COURSE_FAILED",
    
    GET_TOP_6_COURSES_BY_CATEGORY:"GET_TOP_6_COURSES_BY_CATEGORY",
    GET_TOP_6_COURSES_BY_CATEGORY_SUCCESS:"GET_TOP_6_COURSES_BY_CATEGORY_SUCCESS",
    GET_TOP_6_COURSES_BY_CATEGORY_FAILED:"GET_TOP_6_COURSES_BY_CATEGORY_FAILED",
    
    GET_TOP_RATING_COURSE:"GET_TOP_RATING_COURSE",
    GET_TOP_RATING_COURSE_SUCCESS:"GET_TOP_RATING_COURSE_SUCCESS",
    GET_TOP_RATING_COURSE_FAILED:"GET_TOP_RATING_COURSE_FAILED"
}