export const CourseConstant= {
    GET_BEST_SELLER_COURSE: "GET_BEST_SELLER_COURSE",
    GET_BEST_SELLER_COURSE_SUCCESS: "GET_BEST_SELLER_COURSE_SUCCESS",
    GET_BEST_SELLER_COURSE_FAILED: "GET_BEST_SELLER_COURSE_FAILED",
    
    GET_TOP_6_COURSES_BY_CATEGORY:"GET_TOP_6_COURSES_BY_CATEGORY",
    GET_TOP_6_COURSES_BY_CATEGORY_SUCCESS:"GET_TOP_6_COURSES_BY_CATEGORY_SUCCESS",
    GET_TOP_6_COURSES_BY_CATEGORY_FAILED:"GET_TOP_6_COURSES_BY_CATEGORY_FAILED",
    
    GET_TOP_RATING_COURSE:"GET_TOP_RATING_COURSE",
    GET_TOP_RATING_COURSE_SUCCESS:"GET_TOP_RATING_COURSE_SUCCESS",
    GET_TOP_RATING_COURSE_FAILED:"GET_TOP_RATING_COURSE_FAILED",

    GET_CURRENT_COURSES_BY_CATEGORY:"GET_CURRENT_COURSES_BY_CATEGORY",
    GET_CURRENT_COURSES_BY_CATEGORY_SUCCESS:"GET_CURRENT_COURSES_BY_CATEGORY_SUCCESS",
    GET_CURRENT_COURSES_BY_CATEGORY_FAILED:"GET_CURRENT_COURSES_BY_CATEGORY_FAILED",

    GET_COURSE_DETAIL:"GET_COURSE_DETAIL",
    GET_COURSE_DETAIL_SUCCESS:"GET_COURSE_DETAIL_SUCCESS",
    GET_COURSE_DETAIL_SUCCESS_FAIL:"GET_COURSE_DETAIL_SUCCESS_FAIL",

    GET_COURSES_BY_INSTRUCTOR:"GET_COURSES_BY_INSTRUCTOR",
    GET_COURSES_BY_INSTRUCTOR_SUCCESS:"GET_COURSES_BY_INSTRUCTOR_SUCCESS",
    GET_COURSES_BY_INSTRUCTOR_FAIL:"GET_COURSES_BY_INSTRUCTOR_FAIL",

    GET_COURSES_OF_STUDENT:"GET_COURSES_OF_STUDENT",
    GET_COURSES_OF_STUDENT_SUCCESS:"GET_COURSES_OF_STUDENT_SUCCESS",
    GET_COURSES_OF_STUDENT_FAIL:"GET_COURSES_OF_STUDENT_FAIL"
}