export const InstructorConstants = {
    GET_ALL_INSTRUCTORS: "GET_ALL_INSTRUCTORS",
    GET_ALL_INSTRUCTORS_SUCCESS: "GET_ALL_INSTRUCTORS_SUCCESS",
    GET_ALL_INSTRUCTORS_FAILED: "GET_ALL_INSTRUCTORS_FAILED",

    GET_INSTRUCTOR_DETAIL:"GET_INSTRUCTOR_DETAIL",
    GET_INSTRUCTOR_DETAIL_SUCCESS:"GET_INSTRUCTOR_DETAIL_SUCCESS",
    GET_INSTRUCTOR_DETAIL_FAIL:"GET_INSTRUCTOR_DETAIL_FAIL",

}