export const InstructorConstants = {
    GET_ALL_INSTRUCTORS: "GET_ALL_INSTRUCTORS",
    GET_ALL_INSTRUCTORS_SUCCESS: "GET_ALL_INSTRUCTORS_SUCCESS",
    GET_ALL_INSTRUCTORS_FAILED: "GET_ALL_INSTRUCTORS_FAILED",
}