export const LoginConstants = {
    LOGIN: "LOGIN",
    LOGIN_SUCCESS: "LOGIN SUCCESS",
    LOGIN_FAILURE: "LOGIN FAILURE",
    GET_CURRENT_USER: "GET CURRENT USER",
    GET_CURRENT_USER_SUCCESS: "GET CURRENT USER SUCCESS",
    GET_CURRENT_USER_FAILURE: "GET CURRENT USER FAILURE",
    ADMIN_ROLE: "ROLE_ADMIN",
    USER_ROLE: "ROLE_USER",
    LEARNER_ROLE: "ROLE_LEARNER",
    ERROR_MESSAGE: "ERROR MESSAGE"
  }