export const ManagementConstants = {
    LEARNER:"LEARNER",
    COURSE:"COURSE",
    LESSON:"LESSON",
    CATEGORY:"CATEGORY",

    LEARNER_MANAGEMENT:"LEARNER MANAGEMENT",
    COURSE_MANAGEMENT:"COURSE MANAGEMENT",
    LESSON_MANAGEMENT:"LESSON MANAGEMENT",

    CHANGE_MANAGEMENT_SECTION:"CHANGE_MANAGEMENT_SECTION"

}