export const ManagementConstants = {
    LEARNER:"LEARNER",
    COURSE:"COURSE",
    LESSON:"LESSON",
    CATEGORY:"CATEGORY",
    SECTION:"SECTION",

    LEARNER_MANAGEMENT:"LEARNER MANAGEMENT",
    COURSE_MANAGEMENT:"COURSE MANAGEMENT",
    LESSON_MANAGEMENT:"LESSON MANAGEMENT",
    EDIT_LESSON:"EDIT LESSON",
    CREATE_COURSE:"CREATE COURSE",
    SECTION_EDIT:"SECTION EDIT",


    CHANGE_MANAGEMENT_SECTION:"CHANGE_MANAGEMENT_SECTION"

}