export const ManagementConstants = {
    LEARNER:"LEARNER",
    COURSE:"COURSE",
    LESSON:"LESSON",
    CATEGORY:"CATEGORY",
    SECTION:"SECTION",

    LEARNER_MANAGEMENT:"LEARNER MANAGEMENT",
    COURSE_MANAGEMENT:"COURSE MANAGEMENT",
    LESSON_MANAGEMENT:"LESSON MANAGEMENT",
    LESSON_EDIT:"LESSON EDIT",
    LESSON_CREATE:"LESSON CREATE",
    SECTION_CREATE:"SECTION CREATE",
    COURSE_EDIT:"COURSE_EDIT",
    EDIT_LESSON:"EDIT LESSON",
    CREATE_COURSE:"CREATE COURSE",
    SECTION_EDIT:"SECTION EDIT",


    CHANGE_MANAGEMENT_SECTION:"CHANGE_MANAGEMENT_SECTION"

}